djnro/urls.py
from django.urls import include
from django.urls import path
# Uncomment the next two lines to enable the django admin interface:
from django.contrib import admin
admin.autodiscover()
import social_django.urls
from edumanage import views as edumanage_views
import django
import accounts, accounts.views
from django_registration.backends.activation.views import ActivationView

urlpatterns = [
    path("accounts/", include(social_django.urls, namespace='social')),
    path("setlang/", django.views.i18n.set_language, name='set_language'),
    path("admin/", admin.site.urls),
    path('managelogin/<str:backend>/', edumanage_views.manage_login, name='manage_login'),
    path("login/", edumanage_views.user_login, name="login"),
    path("altlogin/", django.contrib.auth.views.LoginView.as_view(template_name='overview/login.html'), name="altlogin"),
    path("logout/", edumanage_views.user_logout, {'next_page': '/'}, name="logout"),
    path('registration/accounts/activate/<path:activation_key>/', accounts.views.activate, name='activate_account'),
    path(
        "registration/activate/complete/",
        ActivationView.as_view(template_name='registration/activation_complete.html'),
        name='registration_activation_complete'
    ),
    path("tinymce/", include('tinymce.urls')),
    path('', include('edumanage.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib import admin
from django.conf import settings
from django.core import validators
from six import python_2_unicode_compatible
from django.utils.translation import gettext_lazy as _
from edumanage.models import Institution
import re


def patch_username_maxlen(field, maxlen=255):
    field.max_length = maxlen
    # try also updating the help_text
    try:
        help_text = field.help_text._proxy____args[0]
        if help_text != None:
            field.help_text = _(re.sub("[0-9]+(?= characters)",
                                       str(maxlen),
                                       help_text))
    except:
        pass
    for v in field.validators:
        if isinstance(v, validators.MaxLengthValidator):
            v.limit_value = maxlen

class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'
        db_table = 'auth_user';
        verbose_name = _('user')
        verbose_name_plural = _('users')
patch_username_maxlen(User._meta.get_field('username'))

@python_2_unicode_compatible
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    is_social_active = models.BooleanField(default=False, verbose_name="Approved")

    class Meta:
        permissions = (
            ("overview", "Can see registered user and respective institutions"),
        )

    def __str__(self):
        return "%s:%s" % (self.user.username, self.institution)

djnro/templates/overview/index.html
{% extends "base.html"%}
{% load i18n %}
{% load tolocale %}
{% load static %}
{% load i18n %}
{% load tolocale %}


{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="col-md-2">
			<div class="push-top"></div>
			<div class="well sidebar-nav">
				<ul class="nav nav-list">
					<li {% block homeactive %}class="active"{% endblock %}>
						<a href="{% url 'overview' %}">{% trans "Overview" %}</a>
					</li>
					<li>
						<form method="POST" action="{% url 'logout' %}">
							{% csrf_token %}
							<button type="submit" class="btn btn-link">{% trans "Logout" %}</button>
						</form>
					</li>
				</ul>
			</div><!--/.well -->
		</div><!--/span-->
		<div class="col-md-10">
			<div class="row">
				<!--/span-->
				<div class="col-md-12">
				{% if violation %}
			  	<table class="table table-condensed">
					    <tr class="error"><td>You have no rights to access this area. Please contact your administrator<td></tr>
					</table>
				{% else %}
              <h4>{% trans "Users - Institutions" %}</h4>
              <hr>
                <ul class="nav nav-tabs">
				    <li class="active"><a href="#users" data-toggle="tab">{% trans "Users" %}</a></li>
				    <li><a href="#institutions" data-toggle="tab">{% trans "Institutions" %}</a></li>
			    </ul>

    			<div class="tab-content" style="margin-top: 20px;">
              		<div class="tab-pane active" id="users">
              		{% if users %}
               			<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" width="100%" id="usertable">
	               			<thead>
								<tr>
									<th>{% trans "Username" %}</th>
									<th>{% trans "Email" %}</th>
									<th>{% trans "Name" %}</th>
									<th>{% trans "Status" %}</th>
									<th>{% trans "Institution" %}</th>
								</tr>
							</thead>
							<tbody>
	                			{% for user in users %}
	              				<tr class="GradeC">
	                				<td>{{user.username}}</td>
	                				<td>{{user.email}}</td>
	                				<td>{{user.first_name}} {{user.last_name}}</td>
	                				<td>
	                					{% if user.userprofile %}
	                						{% if user.userprofile.is_social_active %}
	                							{% trans "Active" %}
	                						{% else %}
	                							{% trans "Inactive" %} or {% trans "Key Expired" %}
	                						{% endif %}
	                					{% else %}-{% endif %}
	                				</td>
	                				<td>{% if user.userprofile.institution %}{% tolocale user.userprofile.institution LANGUAGE_CODE %}{% endif %}</td>
	                			</tr>
	              				{% endfor %}
	              			</tbody>
	              		</table>
	              		{% endif %}
				  	</div>
				  	<div class="tab-pane" id="institutions">
	              		{% if institutions %}
               			<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" width="100%" id="insttable">
	               			<thead>
								<tr>
									<th>{% trans "Name" %}</th>
									<th>{% trans "Type" %}</th>
									<th>{% trans "Contacts" %}</th>
									<th>{% trans "Address" %}</th>
									<th>{% trans "Admin Users" %}</th>
								</tr>
							</thead>
							<tbody>
				                {% for institution in institutions %}
				              	<tr class="GradeC">
				                	<td>{% tolocale institution LANGUAGE_CODE %}</td>
				                	<td>{{institution.get_ertype_display}}</td>
				                	<td>{% if institution.institutiondetails.contact.all %}{% for contact in institution.institutiondetails.contact.all %}{{contact}}<br>{% endfor %}{% endif %}</td>
			                        <td>{% tolocale institution.institutiondetails LANGUAGE_CODE get="address" as institution_institutiondetails_address %}{{institution_institutiondetails_address.street}}<br>{{institution_institutiondetails_address.city}}</td>
				                	<td>{% if institution.userprofile_set.all %}{% for admuser in institution.userprofile_set.all %}{{admuser.user}}<br>{% endfor %}{% endif %}</td>

				                </tr>
				              	{% endfor %}
	              			</tbody>
	              		</table>
	              		{% endif %}
	              	</div>
	             </div>
				{% endif %}
				</div>
			</div>
		</div><!--/span-->
	</div><!--/row-->
</div><!--/.fluid-container-->
{% endblock %}




{% block extrajs %}
<script type="text/javascript" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/plug-ins/505bef35b56/integration/bootstrap/1/dataTables.bootstrap.js"></script>
<script type="text/javascript">
$(document).ready(function(){

var oTableU = $('#usertable').dataTable({
	"sPaginationType": "bootstrap",
	"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
	"aoColumns": [{
        "bSearchable": true,
        "bSortable": true
    }, {
        "bSearchable": true,
        "bSortable": true
    }, {
        "bSearchable": true,
        "bSortable": true
    }, {
        "bSearchable": true,
        "bSortable": true
    }, {
        "bSearchable": true,
        "bSortable": true
    }],
    "aaSorting": [[0, 'desc']],
    "iDisplayLength": 25,
    "oSearch": {"bSmart": false, "bRegex":true},
    "oLanguage": {
    	"sLengthMenu": '{% trans "Display" %} <select><option value="25">25</option><option value="50">50</option><option value="-1">{% trans "All" %}</option></select> {% trans "users" %}',
        "sProcessing":   "Processing...",
        "sZeroRecords": '{% trans "No records to display" %}',
        "sInfo":         "Showing _START_ to _END_ of _TOTAL_ entries",
        "sInfoEmpty":    "{% trans "Showing 0 to 0 of 0 entries" %}",
        "sInfoFiltered": "(filtered from _MAX_ total entries)",
        "sInfoPostFix":  "",
        "sSearch":       '{% trans "Search:" %}',
        "sUrl":          "",
        "oPaginate": {
            "sFirst":    '{% trans "First" %}',
            "sPrevious": '{% trans "Previous" %}',
            "sNext":     '{% trans "Next" %}',
            "sLast":     '{% trans "Last" %}'
        }
    }
});

oTableU.fnDraw();


var oTableI = $('#insttable')
	.on( 'init.dt', function () {
	       	$('.pagination ul').addClass('pagination');
	    })
	.dataTable({
		"sPaginationType": "bootstrap",
		"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
		"aoColumns": [{
	        "bSearchable": true,
	        "bSortable": true
	    }, {
	        "bSearchable": true,
	        "bSortable": true
	    }, {
	        "bSearchable": true,
	        "bSortable": true
	    }, {
	        "bSearchable": true,
	        "bSortable": true
	    }, {
	        "bSearchable": true,
	        "bSortable": true
	    }],
	    "aaSorting": [[0, 'desc']],
	    "iDisplayLength": 25,
	    "oSearch": {"bSmart": false, "bRegex":true},
	    "oLanguage": {
	    	"sLengthMenu": '{% trans "Display" %} <select><option value="25">25</option><option value="50">50</option><option value="-1">{% trans "All" %}</option></select> {% trans "institutions" %}',
	        "sProcessing":   "Processing...",
	        "sZeroRecords": '{% trans "No records to display" %}',
	        "sInfo":         "Showing _START_ to _END_ of _TOTAL_ entries",
	        "sInfoEmpty":    "{% trans "Showing 0 to 0 of 0 entries" %}",
	        "sInfoFiltered": "(filtered from _MAX_ total entries)",
	        "sInfoPostFix":  "",
	        "sSearch":       '{% trans "Search:" %}',
	        "sUrl":          "",
	        "oPaginate": {
	            "sFirst":    '{% trans "First" %}',
	            "sPrevious": '{% trans "Previous" %}',
	            "sNext":     '{% trans "Next" %}',
	            "sLast":     '{% trans "Last" %}'
	        }
	    }
	});

oTableI.fnDraw();

});
</script>
{% endblock %}

djnro/templates/overview/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4">
			<div class="">
				<div class="">
					<h1>Login</h5>
					<hr>
				</div>
				<div class="row">
					<div class="col-md-12">
						<form class="" method="post" action="{% url 'altlogin' %}">
							{% if form.non_field_errors %} {% for err in form.non_field_errors %}
							<div class="form-group error ">
								<div class="controls error">
									<span style="color: #B94A48;">{{err}}</span>
								</div>
							</div>
							{% endfor %} {% endif %} {% csrf_token %}
							<div
								class="form-group {% if form.username.errors %} error {% endif %}">
								<label class="control-label" for="id_username">Username</label>
								<div class="controls">
									{{ form.username }} {% if form.username.errors %} <span
										class="help-inline"> {{ form.username.errors|join:", "}} </span> {% endif %}
								</div>
							</div>
							<div class="form-group {% if form.password.errors %} error {% endif %}">
								<label class="control-label" for="id_password">Password</label>
								<div class="controls">
									{{ form.password }} {% if form.password.errors %} <span
										class="help-inline"> {{ form.password.errors|join:", "}} </span> {% endif %}
								</div>
							</div>
							<div class="form-group">
								<div class="controls">
									<button type="submit" class="btn">Sign in</button>
                                                                        {% if next %}
									<input type="hidden" name="next" value="{{ next }}" />
                                                                        {% else %}
									<input type="hidden" name="next" value="{% url 'overview' %}" />
                                                                        {% endif %}
								</div>
							</div>
						</form>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}